### ISSUE TITLE
Module loading

### ISSUE THREAD

**Issue by VaiTon** [hedgehog1029/Frame#2]
If I am right, modules should invoke`Frame.addModule(MyModule.class);` to register a new module. That's ok but where should they do this? If they are normal jar file and not bukkit plugins they will not be loaded by the server and the plugin now doesn't provide a jar loading system. 
_**So how are modules loaded?**_

**Comment by hedgehog1029** [comment]
Modules should be part of a standard Bukkit plugin. The `Frame.addModule` method should be called inside the `onEnable()` method in your main JavaPlugin class. Sorry, I should have made that clearer in the docs.
